//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGoEquipe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteRendu
    {
        public int idCompteRendu { get; set; }
        public Nullable<System.DateTime> dateCompteRendu { get; set; }
        public string informationsAJour { get; set; }
        public string sommaireRealisationsCompletees { get; set; }
        public string realisationsReportees { get; set; }
        public string etatRisques { get; set; }
        public Nullable<int> idProjet { get; set; }
    
        public virtual Projet Projet { get; set; }
    }
}
