//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGoEquipe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotisation
    {
        public int idCotisation { get; set; }
        public string numTransaction { get; set; }
        public System.DateTime dateTransaction { get; set; }
        public int montant { get; set; }
        public string nomUsager { get; set; }
    
        public virtual Membre Membre { get; set; }
    }
}
