//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGoEquipe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don
    {
        public int IdDon { get; set; }
        public System.DateTime dateDon { get; set; }
        public int montantDon { get; set; }
        public Nullable<int> idDonateur { get; set; }
        public Nullable<int> idLeveeFonds { get; set; }
    
        public virtual Donateur Donateur { get; set; }
        public virtual LeveeFond LeveeFond { get; set; }
    }
}
