//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGoEquipe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBRE
    {
        public string noMembre { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string numeroTel { get; set; }
        public string adresse { get; set; }
        public string motDePasse { get; set; }
        public string dateDabonnement { get; set; }
        public Nullable<bool> inscritMailingListe { get; set; }
        public Nullable<System.DateTime> dateAdhesionMembre { get; set; }
        public Nullable<System.DateTime> statuAdhésionMembre { get; set; }
    }
}
