//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGoEquipe2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetGoDataEntities : DbContext
    {
        public ProjetGoDataEntities()
            : base("name=ProjetGoDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompteRendu> CompteRendus { get; set; }
        public virtual DbSet<Cotisation> Cotisations { get; set; }
        public virtual DbSet<Don> Dons { get; set; }
        public virtual DbSet<Donateur> Donateurs { get; set; }
        public virtual DbSet<Gestion> Gestions { get; set; }
        public virtual DbSet<LeveeFond> LeveeFonds { get; set; }
        public virtual DbSet<Membre> Membres { get; set; }
        public virtual DbSet<Projet> Projets { get; set; }
    }
}
