//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGoEquipe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.CompteRendus = new HashSet<CompteRendu>();
            this.LeveeFonds = new HashSet<LeveeFond>();
        }
    
        public int idProjet { get; set; }
        public string titre { get; set; }
        public string statut { get; set; }
        public string descriptionCourte { get; set; }
        public string sommaire { get; set; }
        public Nullable<System.DateTime> debutEstime { get; set; }
        public Nullable<System.DateTime> finEstimee { get; set; }
        public Nullable<System.DateTime> debutReel { get; set; }
        public Nullable<System.DateTime> finReelle { get; set; }
        public Nullable<double> budget { get; set; }
        public Nullable<double> totalFondsCollectes { get; set; }
        public Nullable<double> totalDepenes { get; set; }
        public string etatAvancement { get; set; }
        public Nullable<int> frequenceComptesRendus { get; set; }
        public Nullable<System.DateTime> dateProchainCompteRendu { get; set; }
        public string idResponsable { get; set; }
        public string visibilite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompteRendu> CompteRendus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeveeFond> LeveeFonds { get; set; }
        public virtual Membre Membre { get; set; }
    }
}
